### ISSUE TITLE
Plugin breaks wordpress oembed

### ISSUE THREAD

**Issue by JanaME** [palasthotel/responsive-oembed#1]
When plugin is activated, the wordpress-oembed for posts don’t work anymore.

Working embed looks like this:
<img width="807" alt="bildschirmfoto 2019-01-07 um 15 37 46" src="https://user-images.githubusercontent.com/4892599/50773861-472a7200-1292-11e9-985d-ffcf6bc24636.png">

<img width="970" alt="bildschirmfoto 2019-01-07 um 15 38 58" src="https://user-images.githubusercontent.com/4892599/50773887-60cbb980-1292-11e9-94f0-cd80324a9782.png">

When plugin is activated the code gets mixed up:
<img width="829" alt="bildschirmfoto 2019-01-07 um 15 40 11" src="https://user-images.githubusercontent.com/4892599/50774069-d9cb1100-1292-11e9-8cce-9a665e90dd56.png">

<img width="974" alt="bildschirmfoto 2019-01-07 um 15 40 57" src="https://user-images.githubusercontent.com/4892599/50774081-e2bbe280-1292-11e9-87a6-1831126237e5.png">

**Comment by greatestview** [comment]
I submitted version 1.4 of this plugin, which excludes WordPress oEmbeds with `data-secret` attribut set, because those are handled via core `wp-embed.js`. Should work for you now.
